# Generated by Django 5.2.6 on 2025-10-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('especialidad', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asignar_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_finalizacion', models.TimeField()),
            ],
        ),
    ]
