# Generated by Django 5.2.6 on 2025-10-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_usuario', models.IntegerField()),
                ('nombre_tipo_usuario', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=20)),
                ('nombres_usuario', models.CharField(max_length=30)),
                ('apellidos_usuarios', models.CharField(max_length=30)),
                ('telefono_usuario', models.CharField(max_length=15)),
                ('direccion_usuario', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
